DROP TABLE administradores CASCADE CONSTRAINTS;

DROP TABLE categorias CASCADE CONSTRAINTS;

DROP TABLE clientes CASCADE CONSTRAINTS;

DROP TABLE contactos CASCADE CONSTRAINTS;

DROP TABLE detalle_pedido CASCADE CONSTRAINTS;

DROP TABLE envios CASCADE CONSTRAINTS;

DROP TABLE estado_envio CASCADE CONSTRAINTS;

DROP TABLE estado_pedido CASCADE CONSTRAINTS;

DROP TABLE metodo_pago CASCADE CONSTRAINTS;

DROP TABLE pedidos CASCADE CONSTRAINTS;

DROP TABLE productos CASCADE CONSTRAINTS;

DROP TABLE promo_productos CASCADE CONSTRAINTS;

DROP TABLE promociones CASCADE CONSTRAINTS;

DROP TABLE roles CASCADE CONSTRAINTS;

DROP TABLE imagenes_producto CASCADE CONSTRAINTS;

CREATE TABLE categorias (
    categoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    descripcion VARCHAR2(200)
);

CREATE TABLE estado_pedido (
    estado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20) NOT NULL UNIQUE
);

CREATE TABLE metodo_pago (
    metodo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20) NOT NULL UNIQUE
);

CREATE TABLE estado_envio (
    estado_envio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE roles (
    rol_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20) NOT NULL UNIQUE
);

---------------------------------------------------------------
-- Tabla Productos

CREATE TABLE productos (
    producto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(500),
    precio NUMBER(10,2) NOT NULL,
    stock NUMBER DEFAULT 0,
    categoria_id NUMBER NOT NULL,
    destacado CHAR(1) DEFAULT 'N' CHECK (destacado IN ('S','N')),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id)
        REFERENCES categorias(categoria_id)
        ON DELETE RESTRICT
);

---------------------------------------------------------------
-- Tabla Clientes

CREATE TABLE clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    telefono VARCHAR2(20),
    direccion VARCHAR2(200),
    usuario VARCHAR2(50),
    password_hash VARCHAR2(255)
);

---------------------------------------------------------------
-- Tabla Pedidos

CREATE TABLE pedidos (
    pedido_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_id NUMBER NOT NULL,
    metodo_id NUMBER NOT NULL,
    total NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(cliente_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_pedido_estado FOREIGN KEY (estado_id)
        REFERENCES estado_pedido(estado_id),
    CONSTRAINT fk_pedido_metodo FOREIGN KEY (metodo_id)
        REFERENCES metodo_pago(metodo_id)
);

---------------------------------------------------------------
-- Tabla DetallePedido

CREATE TABLE detalle_pedido (
    detalle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_detalle_pedido FOREIGN KEY (pedido_id)
        REFERENCES pedidos(pedido_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id)
        REFERENCES productos(producto_id)
);

---------------------------------------------------------------
-- Tabla Envios

CREATE TABLE envios (
    envio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id NUMBER NOT NULL UNIQUE,
    direccion VARCHAR2(200) NOT NULL,
    ciudad VARCHAR2(100) NOT NULL,
    comuna VARCHAR2(100) NOT NULL,
    codigo_postal VARCHAR2(20),
    codigo_seguimiento VARCHAR2(50) UNIQUE,
    estado_envio_id NUMBER NOT NULL,
    costo_envio NUMBER(10,2) DEFAULT 0,
    fecha_envio TIMESTAMP,
    fecha_entrega DATE,
    CONSTRAINT fk_envio_pedido FOREIGN KEY (pedido_id)
        REFERENCES pedidos(pedido_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_envio_estado FOREIGN KEY (estado_envio_id)
        REFERENCES estado_envio(estado_envio_id)
);

---------------------------------------------------------------
-- Tabla Promociones

CREATE TABLE promociones (
    promo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(500),
    descuento_porcentaje NUMBER(5,2) CHECK (descuento_porcentaje BETWEEN 0 AND 100),
    fecha_inicio DATE,
    fecha_fin DATE,
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N'))
);

-- Tabla de varios a varios
CREATE TABLE promo_productos (
    promo_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    CONSTRAINT pk_promo_productos PRIMARY KEY (promo_id, producto_id),
    CONSTRAINT fk_promo FOREIGN KEY (promo_id)
        REFERENCES promociones(promo_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_promo_producto FOREIGN KEY (producto_id)
        REFERENCES productos(producto_id)
);

---------------------------------------------------------------
-- Tabla Contactos

CREATE TABLE contactos (
    contacto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NULL,
    nombre VARCHAR2(100),
    email VARCHAR2(100),
    mensaje VARCHAR2(1000),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contacto_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(cliente_id)
        ON DELETE SET NULL
);

---------------------------------------------------------------
-- Tabla Administradores

CREATE TABLE administradores (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    rol_id NUMBER NOT NULL,
    CONSTRAINT fk_admin_rol FOREIGN KEY (rol_id)
        REFERENCES roles(rol_id)
);

----------------------------------------------------------------
---Tabla imagenes 

CREATE TABLE imagenes_producto (
    imagen_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id NUMBER NOT NULL,
    url_imagen VARCHAR2(255) NOT NULL,
    FOREIGN KEY (producto_id) REFERENCES productos(producto_id)
);
