DROP TABLE administradores CASCADE CONSTRAINTS;

DROP TABLE categorias CASCADE CONSTRAINTS;

DROP TABLE clientes CASCADE CONSTRAINTS;

DROP TABLE contactos CASCADE CONSTRAINTS;

DROP TABLE detalle_pedido CASCADE CONSTRAINTS;

DROP TABLE envios CASCADE CONSTRAINTS;

DROP TABLE estado_envio CASCADE CONSTRAINTS;

DROP TABLE estado_pedido CASCADE CONSTRAINTS;

DROP TABLE metodo_pago CASCADE CONSTRAINTS;

DROP TABLE pedidos CASCADE CONSTRAINTS;

DROP TABLE productos CASCADE CONSTRAINTS;

DROP TABLE promo_productos CASCADE CONSTRAINTS;

DROP TABLE promociones CASCADE CONSTRAINTS;

DROP TABLE roles CASCADE CONSTRAINTS;



-- Tabla Categorías
---------------------------------------------------------------

CREATE TABLE categorias (
    categoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    descripcion VARCHAR2(200)
);


-- Tabla Estado de Pedido
---------------------------------------------------------------

CREATE TABLE estado_pedido (
    estado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE
);


-- Tabla Estado de Pago 
---------------------------------------------------------------

CREATE TABLE estado_pago (
    estado_pago_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE
);


-- Tabla Método de Pago
---------------------------------------------------------------

CREATE TABLE metodo_pago (
    metodo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20) NOT NULL UNIQUE
);


-- Tabla Estado Envío
---------------------------------------------------------------

CREATE TABLE estado_envio (
    estado_envio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE
);


-- Tabla Roles
---------------------------------------------------------------

CREATE TABLE roles (
    rol_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20) NOT NULL UNIQUE
);


-- Tabla Productos 
---------------------------------------------------------------

CREATE TABLE productos (
    producto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(500),
    precio NUMBER(10,2) NOT NULL,
    peso_kg NUMBER(8,3) DEFAULT 0,
    stock NUMBER DEFAULT 0,
    categoria_id NUMBER NOT NULL,
    destacado CHAR(1) DEFAULT 'N' CHECK (destacado IN ('S','N')),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id)
        REFERENCES categorias(categoria_id)
        ON DELETE RESTRICT
);


-- Tabla Clientes
---------------------------------------------------------------

CREATE TABLE clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    telefono VARCHAR2(20),
    direccion VARCHAR2(200),
    usuario VARCHAR2(50),
    password_hash VARCHAR2(255)
);


-- Tabla Pedidos 
---------------------------------------------------------------

CREATE TABLE pedidos (
    pedido_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER,
    nombre VARCHAR2(100),
    direccion VARCHAR2(255),
    comuna VARCHAR2(100),
    telefono VARCHAR2(20),
    email VARCHAR2(100),

    estado_id NUMBER NOT NULL,
    estado_pago_id NUMBER,
    metodo_id NUMBER NOT NULL,

    total NUMBER(10,2) NOT NULL,
    tipo_entrega VARCHAR2(20) DEFAULT 'delivery',
    blue_code NUMBER,
    costo_envio_min NUMBER DEFAULT 0,
    costo_envio_max NUMBER DEFAULT 0,
    payment_id VARCHAR2(200),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ticket_url VARCHAR2(500),

    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(cliente_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_pedido_estado FOREIGN KEY (estado_id)
        REFERENCES estado_pedido(estado_id),

    CONSTRAINT fk_pedido_estado_pago FOREIGN KEY (estado_pago_id)
        REFERENCES estado_pago(estado_pago_id),

    CONSTRAINT fk_pedido_metodo FOREIGN KEY (metodo_id)
        REFERENCES metodo_pago(metodo_id)
);


-- Tabla DetallePedido
---------------------------------------------------------------

CREATE TABLE detalle_pedido (
    detalle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id NUMBER NOT NULL,
    producto_id NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    peso_unitario NUMBER(8,3) DEFAULT 0,
    peso_total_item NUMBER(8,3) DEFAULT 0,

    CONSTRAINT fk_detalle_pedido FOREIGN KEY (pedido_id)
        REFERENCES pedidos(pedido_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id)
        REFERENCES productos(producto_id)
);


-- Tabla Envíos
---------------------------------------------------------------

CREATE TABLE envios (
    envio_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id NUMBER NOT NULL UNIQUE,
    direccion VARCHAR2(200) NOT NULL,
    ciudad VARCHAR2(100) NOT NULL,
    comuna VARCHAR2(100) NOT NULL,
    codigo_postal VARCHAR2(20),
    codigo_seguimiento VARCHAR2(50) UNIQUE,
    estado_envio_id NUMBER NOT NULL,
    costo_envio NUMBER(10,2) DEFAULT 0,
    fecha_envio TIMESTAMP,
    fecha_entrega DATE,

    CONSTRAINT fk_envio_pedido FOREIGN KEY (pedido_id)
        REFERENCES pedidos(pedido_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_envio_estado FOREIGN KEY (estado_envio_id)
        REFERENCES estado_envio(estado_envio_id)
);


-- Tabla Contactos
---------------------------------------------------------------

CREATE TABLE contactos (
    contacto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NULL,
    nombre VARCHAR2(100),
    email VARCHAR2(100),
    mensaje VARCHAR2(1000),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    respondido CHAR(1) DEFAULT 'N',

    CONSTRAINT fk_contacto_cliente FOREIGN KEY (cliente_id)
        REFERENCES clientes(cliente_id)
        ON DELETE SET NULL
);


-- Tabla Administradores
---------------------------------------------------------------

CREATE TABLE administradores (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    rol_id NUMBER NOT NULL,

    CONSTRAINT fk_admin_rol FOREIGN KEY (rol_id)
        REFERENCES roles(rol_id)
);


-- Tabla Imagenes Producto
---------------------------------------------------------------

CREATE TABLE imagenes_producto (
    imagen_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id NUMBER NOT NULL,
    url_imagen VARCHAR2(255) NOT NULL,

    FOREIGN KEY (producto_id) REFERENCES productos(producto_id)
);
